include: package:lint/analysis_options.yaml

linter:
  rules:
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
